background=../assets/floor_.png
circuit=../assets/circuit4.png
bitmask=../assets/black_map4.png

initialX=0.65
initialY=0.0

spaceMaxW=1.0
spaceMaxH=1.0
# limite de 2 porque só tem alguns indices no source